package springhibernateswingcrud;
// Generated Mar 15, 2017 10:08:42 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * Employee generated by hbm2java
 */
//@Entity
public class Employee {

//     @Id
     private Integer id;
     private String name;
     private double salary;

    public Employee() {
    }

    public Employee(Integer id) {
        this.id = id;
    }

    public Employee(String name, double salary) {
        this.name = name;
        this.salary = salary;
    }

    

    @Override
    public String toString() {
        return "Employee{" + "id=" + id + ", name=" + name + ", salary=" + salary + '}';
    }

    public Employee(Integer id, String name, double salary) {
        this.id = id;
        this.name = name;
        this.salary = salary;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getSalary() {
        return this.salary;
    }
    
    public void setSalary(double salary) {
        this.salary = salary;
    }




}


